#I have altered the file. Pray I do not alter it further!
url: "https://www.brandonalafleur.com"

#Site Settings
title: Brandon LaFleur
email: brandon.a.lafleur@gmail.com
description: Developer and IT Professional
theme: jekyll-theme-midnight
repository: DIGITALD0GMA/DIGITALD0GMA.github.io
highlighter: rouge